spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAGAHR558KD3Y6dyjTaKvLwsMa5G4FdTSttuvxS6YN5qc5MYJB/LV41k18K+QgKOkKp6GfnfrqkUqqzPmUoV6M5Ms11JnpRQ5arsmY5oo+WOXNmUT+PAKWZ051atYngI6gNURNTYw2eHWzTqgywzgTDLj1NT8X94q3Ir5KuWeJMLCIzw442zUpPcDvfpl4YSE2n1KZ2vqncslNDfqPxeZGMJDKceIRspMRtnBbrtNA6hvqsX2XFYPQlf7HpBZ4XorMcLe+Ki+GJKcWJYE/4YPkgpBuNlwK9Y4WQQPqbAI7ghfAqmADyJSkFQ+nG+S0ho0lmmgJcTw7EwSkL/vd3Br6k3u0kCBa9Mylrp9tyRBxwDQMvR3bRDHAKDiils0pu8wQ='
  
# token:
#   expiration_time: 86400000 # 만료 기간 -> 하루
#   secret: '{cipher}AQBr7zVkg9ilfUqJYsHQag/30IeJ0V7rfEnYFdviZP4OD2giykMG4o8cXH0JyFuCEqJCnp4V3Nm1/KH4GwAKddRH010ggTo3ltvBtcTRCs1hKaWlcn0NFB28/Ri7n83QRZou2V2FUsOoM52meynjZ6I9i6grDfzMVQXm8TtXe47xqmeLp0vT1vxZYVfnHWOeFn+0Iix+W70dtsSm+1A9FvQsaqVqkfoB0ECue0JriG9LbLXjYvFg/eo08clL5SAIqY46uLATBc2teN30v1nv5nZ+u8DAgVFkiIhN2nalaNprji9nsP4JHsHaJ+RpgsFY7BZThkXKxlRQNfkzf8TbONiIBvCx90YgQWn/LL5lDQ6x5qCAeiBPlyo5j/09bLHAGtE=' # 토큰 키
# gateway:
#   ip: 127.0.0.1

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    orders_is_empty: There is no item.
